config/routes.rb
Rails.application.routes.draw do
  root to: "songs#index"

  resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id          :integer          not null, primary key
#  album       :string
#  artist      :string
#  cover_image :string
#  duration    :time
#  name        :string
#  position    :integer
#  url         :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Song < ApplicationRecord
  # serialize :song
  # /\A(?!00:00)[0-5][0-9]:[0-5][0-9]\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[show edit update destroy]

  def index
    @songs = Song.all
    songs_ids = @songs.map(&:id)
    respond_to do |format|
      format.html
      format.json { render json: @songs }
    end
  end

  def show
    render json: @song
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      respond_to do |format|
      format.html
      format.js { render json: @song }
    end
      redirect_to songs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @song.update(song_params)
    if @song.save
      redirect_to songs_path
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to root_path
  end

  private

  def song_params
    params.require(:song).permit(:name, :artist, :album, :url, :cover_image, :duration, :position)
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tailwind_form_builder.rb
class TailwindFormBuilder < ActionView::Helpers::FormBuilder
  def text_field(method, opts={})
    default_opts = { class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 #{'border-2 border-red-500' if @object.errors.any?}" }
    merged_opts = default_opts.merge(opts)
    super(method, merged_opts)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audioplay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
      <%= yield %>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/amplitudejs@5.3.2/dist/amplitude.js"></script>
  </body>
</html>

app/views/songs/_form.html.erb
<div class="md:container md:mx-auto">
<h1 class="text-center text-white my-5 py-5">FORM SONG</h1>
<%= form_with model: song, builder: TailwindFormBuilder do |form| %>
  <% if form.object.errors.any? %>
    <div class="m-3">
      <% form.object.errors.full_messages.each do |error| %>
        <div><%= error %></div>
      <% end %>
    </div>
  <% end %>
  <div class="container mx-auto w-9/12">
    <div class="flex flex-col m-3">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="flex flex-col m-3">
      <%= form.label :album %>
      <%= form.text_field :album %>
    </div>

    <div class="flex flex-col m-3">
      <%= form.label :artist %>
      <%= form.text_field :artist %>
    </div>

    <div class="flex flex-col m-3">
      <%= form.label :url %>
      <%= form.text_field :url %>
    </div>

    <div class="flex flex-col m-3">
      <%= form.label :cover_image %>
      <%= form.text_field :cover_image %>
    </div>

    <div class="flex flex-col mx-auto items-center w-2/12 m-3">
      <%= form.label :position %>
      <%= form.number_field :position, class: "mt-1 block rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
    </div>

    <div class="flex flex-col text-center mx-auto w-2/12 m-3">
      <%= form.label :duration %>
      <%= form.time_select :duration %>
    </div>
    <div class="text-center">
      <%= form.button class:"middle none center mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-black shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
      <%= link_to "delete song", song_path(song), method: :delete if params[:action] == 'edit' %>
    </div>
  <% end %>
</div>
</div>

app/views/songs/edit.html.erb
<h1>Edit</h1>
<%= render 'form', song: @song %>

app/views/songs/index.html.erb
<div class="flex flex-col items-center m-5">
  <%= link_to 'New Song', new_song_path, class:'bg-blue-500 hover:bg-blue-700 text-white font-bold m-3 py-2 px-4 rounded' %>
</div>
<div id="flat-black-player-container" data-controller="audio" data-howler-url-value="/songs">
      <div id="list-screen" class="slide-in-top">
        <div id="list-screen-header" class="hide-playlist">
          <img id="up-arrow" src="https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/up.svg"/>
          Hide Playlist
        </div>

        <div id="list">
          <% @songs.order(position: :asc).each_with_index do |song, i| %>
          <div class="song amplitude-song-container amplitude-play-pause" data-amplitude-song-index="<%= i %>">
            <span class="song-number-now-playing">
              <span class="number"><%= i + 1 %></span>
              <img class="now-playing" src="https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/now-playing.svg"/>
            </span>

            <div class="song-meta-container">
              <span class="song-name" data-amplitude-song-info="name" data-amplitude-song-index="<%= i %>"></span>
              <span class="song-artist-album"><span data-amplitude-song-info="artist" data-amplitude-song-index="<%= i %>"></span> - <span data-amplitude-song-info="album" data-amplitude-song-index="<%= i %>"></span><span> - <%= link_to '[edit info]', edit_song_path(song) %></span></span>
            </div>

            <span class="song-duration">
              <%= song.duration.strftime("%H:%M") %>
            <span>
          </div>
          <% end -%>
        </div>
      </div>
      <div id="player-screen">
        <div class="player-header down-header">
          <img id="down" src="https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/down.svg"/>
          Show Playlist
        </div>
        <div id="player-top">
          <img data-amplitude-song-info="cover_art_url"/>
        </div>
        <div id="player-progress-bar-container">
          <progress id="song-played-progress" class="amplitude-song-played-progress"></progress>
          <progress id="song-buffered-progress" class="amplitude-buffered-progress" value="0"></progress>
        </div>
        <div id="player-middle">
          <div id="time-container">
            <span class="amplitude-current-time time-container"></span>
            <span class="amplitude-duration-time time-container"></span>
          </div>
          <div id="meta-container">
            <span data-amplitude-song-info="name" class="song-name"></span>

            <div class="song-artist-album">
              <span data-amplitude-song-info="artist"></span>
            </div>
          </div>
        </div>
        <div id="player-bottom">
          <div id="control-container">

            <div id="shuffle-container">
              <div class="amplitude-shuffle amplitude-shuffle-off" id="shuffle"></div>
            </div>

            <div id="prev-container">
              <div class="amplitude-prev" id="previous"></div>
            </div>

            <div id="play-pause-container">
              <div class="amplitude-play-pause" id="play-pause"></div>
            </div>

            <div id="next-container">
              <div class="amplitude-next" id="next"></div>
            </div>

            <div id="repeat-container">
              <div class="amplitude-repeat" id="repeat"></div>
            </div>

          </div>

          <div id="volume-container">
            <img src="https://521dimensions.com/img/open-source/amplitudejs/examples/flat-black/volume.svg"/><input type="range" class="amplitude-volume-slider" step=".1"/>
          </div>
        </div>
      </div>
    </div>

app/views/songs/new.html.erb
<h1>New</h1>
<%= render 'form', song: @song %>